#!/bin/bash
CONFIG_DIR=$HOME/.config/sketchybar
source $CONFIG_DIR/colors.sh
echo $BAR_BACKGROUND
options=(
	style=square
	width=6.0
	active_color=$BAR_BACKGROUND
	inactive_color=$BAR_BACKGROUND
)

borders "${options[@]}"

