tap "daipeihust/tap"
tap "felixkratz/formulae"
tap "homebrew/bundle"
tap "homebrew/services"
tap "koekeishiya/formulae"
brew "act"
brew "xz"
brew "jpeg-xl"
brew "aom"
brew "python@3.11"
brew "awscli"
brew "bat"
brew "btop"
brew "cowsay"
brew "exiftool"
brew "eza"
brew "fastfetch"
brew "fd"
brew "unbound"
brew "tesseract"
brew "ffmpeg"
brew "fortune"
brew "fzf"
brew "gh"
brew "git"
brew "git-flow"
brew "htop"
brew "hyperfine"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "lolcat"
brew "mas"
brew "midnight-commander"
brew "ncdu"
brew "neovim"
brew "nnn"
brew "node"
brew "openjdk"
brew "pfetch"
brew "pipx"
brew "pngpaste"
brew "poppler"
brew "postgresql@14"
brew "pre-commit"
brew "ranger", args: ["HEAD"]
brew "ripgrep"
brew "sox"
brew "speedtest-cli"
brew "starship"
brew "virtualenv"
brew "watch"
brew "wget"
brew "yazi"
brew "zoxide"
brew "daipeihust/tap/im-select"
brew "felixkratz/formulae/borders"
brew "felixkratz/formulae/sketchybar"
brew "felixkratz/formulae/svim"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
cask "1password"
cask "1password-cli"
cask "aethersx2"
cask "aldente"
cask "anki"
cask "arq"
cask "blackhole-2ch"
cask "clipy"
cask "cyberduck"
cask "daisydisk"
cask "dictionaries"
cask "discord"
cask "fliqlo"
cask "font-3270-nerd-font"
cask "font-daddy-time-mono-nerd-font"
cask "font-fira-code-nerd-font"
cask "font-im-writing-nerd-font"
cask "font-inconsolata-nerd-font"
cask "font-iosevka-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-victor-mono-nerd-font"
cask "fontsmoothingadjuster"
cask "google-chrome"
cask "iina"
cask "imageoptim"
cask "imazing"
cask "inssider"
cask "jellyfin"
cask "karabiner-elements"
cask "keep-it"
cask "keyboardcleantool"
cask "kitty"
cask "latest"
cask "ledger-live"
cask "macdown"
cask "macs-fan-control"
cask "obs"
cask "obsidian"
cask "onyx"
cask "openemu"
cask "orbstack"
cask "poedit"
cask "private-internet-access"
cask "pycharm-ce"
cask "rapidapi"
cask "raycast"
cask "setapp"
cask "sf-symbols"
cask "slack"
cask "spotify"
cask "telegram"
cask "telegram-desktop"
cask "the-unarchiver"
cask "transmission"
cask "ukelele"
cask "viber"
cask "vnc-viewer"
cask "wezterm"
cask "whisky"
cask "xscreensaver"
cask "zed"
mas "1Password for Safari", id: 1569813296
mas "Amphetamine", id: 937984704
mas "Apple Configurator", id: 1037126344
mas "Banktivity", id: 1480779512
mas "Converter", id: 1457309557
mas "Dark Reader for Safari", id: 1438243180
mas "Disk Speed Test", id: 425264550
mas "DjVu Reader", id: 733144595
mas "Documents Translator", id: 1566993561
mas "Home Assistant", id: 1099568401
mas "Keynote", id: 409183694
mas "LanScan", id: 472226235
mas "Linearity Curve", id: 1219074514
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator Pro", id: 1289583905
mas "rcmd", id: 1596283165
mas "Shortery", id: 1594183810
mas "Speedtest", id: 1153157709
mas "Stitcher", id: 1492912652
mas "Streaks", id: 963034692
mas "Things", id: 904280696
mas "TV Remote", id: 1535056536
mas "Vimari", id: 1480933944
