# Common settings

set -g mouse on
set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"


# Common key bindings

bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"


# Look and feel

set -g status-bg "color0"
set -g status-fg "color15"
set -g status 2
set -g 'status-format[1]' '#[fill=terminal]'
set-option -g status-position top

set -g pane-border-format '#[align=centre bold]#[reverse]#{pane_title}#[default]'
set -g pane-border-status off
set-hook -g 'after-split-window' 'if-shell -F "#{!=:#{window_panes},1}" "set -g pane-border-status top"'
set-hook -g 'after-kill-pane' 'if-shell -F "#{==:#{window_panes},1}" "set -g pane-border-status off"'
set-hook -g 'pane-exited' 'if-shell -F "#{==:#{window_panes},1}" "set -g pane-border-status off"'
