#!/usr/bin/env bash

ACTIVE_WINDOW_OPACITY=1.0
NORMAL_WINDOW_OPACITY=0.5

common_settings() {
    echo "Setting common settings for Yabai"
    padding=10
    yabai -m config layout bsp
    yabai -m config external_bar all:48:0
    yabai -m config window_gap $padding
    yabai -m config top_padding 0
    yabai -m config bottom_padding $padding
    yabai -m config left_padding $padding
    yabai -m config right_padding $padding
    yabai -m config mouse_follows_focus on
    yabai -m config window_placement second_child
    yabai -m config window_opacity on
    yabai -m config active_window_opacity $ACTIVE_WINDOW_OPACITY
    yabai -m config normal_window_opacity $NORMAL_WINDOW_OPACITY
    yabai -m config window_opacity_duration 0.1
}

rules() {
    echo "Setting rules for Yabai"
    yabai -m rule --add app=Endel manage=off
    yabai -m rule --add app=Step\ Two manage=off
}

signals() {
    yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
    yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
    yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
    # https://github.com/koekeishiya/yabai/issues/1916
    yabai -m signal --add event=window_focused action="yabai -m window recent --opacity $NORMAL_WINDOW_OPACITY; yabai -m window --opacity 0.0"
    yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
    sudo /opt/homebrew/bin/yabai --load-sa
}

set_space_to_bsp() {
    echo "Setting space $1 to bsp layout"
    yabai -m space $1 --layout bsp
}

set_space_to_webdev() {
    set_space_to_bsp $1
    echo "Setting space $1 to webdev layout"
    browser_id=$(yabai -m query --windows --space $1 | jq '.[] | select(.app == "Orion") | .id')
    nvim_id=$(yabai -m query --windows --space $1 | jq '.[] | select(.title|endswith("- Nvim")) | .id')
    if [ -z "$nvim_id" ]; then
        nvim_id="first"
    fi
    yabai -m space $1 --balance
    yabai -m window $browser_id --swap last
    yabai -m window $nvim_id --focus
    yabai -m window $nvim_id --ratio abs:0.80
    yabai -m window $browser_id --ratio abs:0.75
}

set_space_to_stack() {
    echo "Setting space $1 to stacked layout"
    yabai -m space $1 --layout stack
}

if [ "$1" = "set_space_to_bsp" ]; then
    set_space_to_bsp "$2"
elif [ "$1" = "set_space_to_webdev" ]; then
    set_space_to_webdev "$2"
elif [ "$1" = "set_space_to_stack" ]; then
    set_space_to_stack "$2"
else
    echo "Loading full Yabai configuration"
    common_settings
    rules
    signals
fi
