#!/bin/sh

common_settings()
{
    echo "Setting common settings for Yabai"
    yabai -m config external_bar all:48:0
    # yabai -m config window_gap 20
    yabai -m config window_gap 5
    yabai -m config mouse_follows_focus on
    yabai -m config window_placement second_child
    yabai -m config window_opacity off
    yabai -m config active_window_opacity 1.0
    yabai -m config normal_window_opacity 0.5
}

set_space_labels()
{
    echo "Settings labels for spaces"
    yabai -m space 1 --label web
    yabai -m space 2 --label mnge
    yabai -m space 3 --label comm
    yabai -m space 4 --label dev
}

signals()
{
    yabai -m signal --add event=display_added action="sh ~/.yabairc update_all_spaces"
    yabai -m signal --add event=display_removed action="sh ~/.yabairc update_all_spaces"
    yabai -m signal --add event=display_resized action="sh ~/.yabairc update_all_spaces"
    yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
    yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
    yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
    yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
    sudo yabai --load-sa
}


set_space_to_bsp()
{
    echo "Setting space $1 to bsp layout"
    yabai -m space $1 --layout bsp
    # yabai -m space $1 --padding abs:20:20:20:20
    yabai -m space $1 --padding abs:0:0:0:0
}

set_space_to_stack()
{
    echo "Setting space $1 to stacked layout"
    yabai -m space $1 --layout stack
    yabai -m space $1 --padding abs:0:0:0:0
}


update_all_spaces()
{
    echo "Updating all spaces on all displays"
    display_list=$(yabai -m query --displays)
    display_count=$(echo $display_list | jq ". | length")
    echo d_count $display_count
    for ((d=0; d<$display_count; d++)); do
        display_width=$(echo $display_list | jq ".[$d].frame.w")
        space_list=$(echo $display_list | jq ".[$d].spaces")
        space_count=$(echo $space_list | jq ". | length")
        echo s_count $space_count
        for ((s=0; s<$space_count; s++)); do
            space_number=$(echo $space_list | jq ".[$s]")
            if [ $display_width -gt 1800 ]; then
                # External monitor
                set_space_to_bsp $space_number
            else
                # Laptop screen
                set_space_to_stack $space_number
            fi
        done

    done

}

if [ $1 = "update_all_spaces" ]; then
    update_all_spaces
elif [ $1 = "set_space_to_bsp" ]; then
    set_space_to_bsp $2
elif [ $1 = "set_space_to_stack" ]; then
    set_space_to_stack $2
else
    echo "Loading full Yabai configuration"
    common_settings
    set_space_labels
    update_all_spaces
    signals
fi
