-- vim.api.nvim_create_autocmd("InsertLeave", {
--     pattern = { "*" },
--     callback = function()
--         os.execute("im-select com.evgkirov.keyboardlayout.custom.keylayout.ENSR")
--     end,
-- })
