return {
    "nvim-treesitter/nvim-treesitter",
    event = "BufEnter",
    main = "nvim-treesitter.configs",
    config = true,
    opts = {
        ensure_installed = {
            "bash",
            "comment",
            "css",
            "csv",
            "diff",
            "dockerfile",
            "fish",
            "gitattributes",
            "git_config",
            "gitcommit",
            "gitignore",
            "git_rebase",
            "html",
            "htmldjango",
            "ini",
            "javascript",
            "jsdoc",
            "json",
            "json5",
            "lua",
            "luadoc",
            "luau",
            "make",
            "markdown",
            "markdown_inline",
            "po",
            "python",
            "regex",
            "requirements",
            "rst",
            "scss",
            "sql",
            "ssh_config",
            "toml",
            "tsx",
            "typescript",
            "xml",
            "yaml",
        },
        highlight = {
            enable = true,
        }
    },
}
