#!/usr/bin/env bash

# prefer icons prefixed with nf-md-
get_app_icon() {
    case $1 in
    "1Password") echo 󱉼 ;;
    "Activity Monitor") echo 󱕎 ;;
    "AetherSX2") echo  ;;
    "AlDente") echo 󱅠 ;;
    "Anki") echo 󰓎 ;;
    "App Store") echo  ;;
    "Arq") echo  ;;
    "AWS VPN Client") echo 󱇱 ;;
    "Banktivity") echo 󰁰 ;;
    "BetterDisplay") echo 󰨇 ;;
    "Blender") echo 󰂫 ;;
    "Books") echo 󱓷 ;;
    "Calculator") echo 󰃬 ;;
    "Calendar") echo 󰸗 ;;
    "ChatGPT") echo 󰧑 ;;
    "CleanMyMac") echo 󰃢 ;;
    "Clock") echo 󰥔 ;;
    "Contacts") echo 󰛋 ;;
    "Cyberduck") echo 󰇥 ;;
    "Dash") echo D ;;
    "Day One") echo 󰃀 ;;
    "Dictionary") echo 󰗊 ;;
    "Discord") echo 󰙯 ;;
    "Docker Desktop") echo 󰡨 ;;
    "Docker") echo 󰡨 ;;
    "Endel") echo 󰥛 ;;
    "FaceTime") echo 󰕧 ;;
    "Fantastical") echo 󰸗 ;;
    "Figma") echo  ;;
    "Find My") echo 󰐷 ;;
    "Finder") echo 󰀶 ;;
    "FreeCAD") echo  ;;
    "Fusion") echo 󰬍 ;;
    "Ghostty") echo 󰞷 ;;
    "GitHub Desktop") echo 󰊤 ;;
    "GitKraken") echo  ;;
    "Google Chrome Canary") echo 󰊯 ;;
    "Google Chrome") echo 󰊯 ;;
    "Google Meet") echo 󰕧 ;;
    "Hand Mirror") echo 󱇽 ;;
    "Home Assistant") echo 󰟐 ;;
    "Home") echo 󰋜 ;;
    "IINA") echo 󰐊 ;;
    "iPhone Mirroring") echo  ;;
    "iTerm2") echo 󰞷 ;;
    "Keynote") echo 󰐨 ;;
    "Ledger Live") echo 󰖄 ;;
    "Little Snitch Network Monitor") echo 󰈐 ;;
    "Little Snitch") echo 󰈐 ;;
    "MacDown") echo  ;;
    "Macs Fan Control") echo 󰈐 ;;
    "Mail") echo 󰇮 ;;
    "Maps") echo 󰦂 ;;
    "Menu Bar Controller for Sonos") echo 󰐎 ;;
    "Messages") echo 󰭹 ;;
    "MindNode") echo 󰌪 ;;
    "MultiViewer for F1") echo 󰶓 ;;
    "Music") echo 󰝚 ;;
    "Neovide") echo  ;;
    "Notes") echo 󰎞 ;;
    "Numbers") echo 󰄨 ;;
    "OBS Studio") echo  ;;
    "Obsidian") echo 󰇈 ;;
    "OrbStack") echo 󰡨 ;;
    "OrcaSlicer") echo 󱢴 ;;
    "Orion") echo 󰫢 ;;
    "Pages") echo 󰏪 ;;
    "Phanpy") echo 󰫑 ;;
    "Photos") echo  ;;
    "Pixelmator Pro") echo 󰃣 ;;
    "Podcasts") echo 󰦔 ;;
    "Poedit") echo 󰗊 ;;
    "Postico") echo 󰟆 ;;
    "Preview") echo 󰋩 ;;
    "PyCharm CE") echo 󰌠 ;;
    "PyCharm") echo 󰌠 ;;
    "QuickTime Player") echo  ;;
    "Rakuten Viber") echo 󰖣 ;;
    "Raycast") echo 󰍉 ;;
    "Reminders") echo 󰝖 ;;
    "Rocket.Chat") echo 󱓞 ;;
    "Safari") echo 󰀹 ;;
    "Session") echo 󰁫 ;;
    "Setapp") echo 󰣏 ;;
    "Shortcuts") echo  ;;
    "Slack") echo 󰒱 ;;
    "Sonos") echo 󰓃 ;;
    "Spotify") echo 󰓇 ;;
    "Steam Helper") echo 󰓓 ;;
    "Steam") echo 󰓓 ;;
    "Stocks") echo 󰄪 ;;
    "Sublime Text") echo 󰰡 ;;
    "System Settings") echo 󰒓 ;;
    "TablePlus") echo 󰟆 ;;
    "Telegram Desktop") echo  ;;
    "Telegram") echo  ;;
    "Things") echo 󰄲 ;;
    "Timing") echo 󰥔 ;;
    "Tower") echo 󰴾 ;;
    "Transmission") echo 󰇚 ;;
    "TV") echo 󰠹 ;;
    "Twitter") echo 󰕄 ;;
    "Ukelele") echo  ;;
    "Upwork") echo 󰰨 ;;
    "Weather") echo 󰖕 ;;
    "WezTerm") echo  ;;
    "WhatsApp (old)") echo 󰖣 ;;
    "WhatsApp") echo 󰖣 ;;
    "X") echo 󰕄 ;;
    "YouTube") echo 󰗃 ;;
    "Zed") echo 󰰶 ;;
    "zoom.us") echo 󰕧 ;;
    *) echo 󰘔 ;;
    esac
}

get_app_icon "$1"
