require("plugins")
require("colorscheme")
require("commands")
require("keymap")
require("settings")

require("setup-__experiments")
require("setup-bufferline")
require("setup-cmp")
require("setup-nvim-surround")
require("setup-nvim-tree")
require("setup-telescope")
require("setup-which-key")
